### ISSUE TITLE
Getting following error during following step: Install required packages

### ISSUE THREAD

**Issue by js333031** [Tony607/object_detection_demo#22]
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
/content/models/research
2020-04-25 12:02:37.429554: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "/content/models/research/object_detection/builders/model_builder.py", line 22, in <module>
    from object_detection.builders import box_predictor_builder
  File "/content/models/research/object_detection/builders/box_predictor_builder.py", line 20, in <module>
    from object_detection.predictors import convolutional_box_predictor
  File "/content/models/research/object_detection/predictors/convolutional_box_predictor.py", line 23, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'

**Comment by BankPC** [comment]
I found that this notebook is built on TF 1.x while currently the Colab using TF2.x as default. You just specify the TF version before running the notebook as
`%tensorflow_version 1.x`
Then, you can run this notebook.
