### ISSUE TITLE
ModuleNotFoundError: No module named 'tf_slim'

### ISSUE THREAD

**Issue by DennisFaucher** [Tony607/object_detection_demo#30]
Thanks for the notebook.

The "Install required packages" step fails in Google Colab with the above error. Any ideas? TIA

Setting up python-html5lib (0.999999999-1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
/content/models/research
object_detection/protos/input_reader.proto: warning: Import object_detection/protos/image_resizer.proto but not used.
2020-07-08 21:34:28.642960: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 21, in <module>
    from object_detection.builders import model_builder
  File "/content/models/research/object_detection/builders/model_builder.py", line 19, in <module>
    from object_detection.builders import anchor_generator_builder
  File "/content/models/research/object_detection/builders/anchor_generator_builder.py", line 23, in <module>
    from object_detection.anchor_generators import flexible_grid_anchor_generator
  File "/content/models/research/object_detection/anchor_generators/flexible_grid_anchor_generator.py", line 19, in <module>
    from object_detection.anchor_generators import grid_anchor_generator
  File "/content/models/research/object_detection/anchor_generators/grid_anchor_generator.py", line 27, in <module>
    from object_detection.utils import ops
  File "/content/models/research/object_detection/utils/ops.py", line 28, in <module>
    import tf_slim as slim
ModuleNotFoundError: No module named 'tf_slim'

**Comment by DennisFaucher** [comment]
Fixed. Added "!pip install tf_slim" before this section.
